### ISSUE TITLE
User can choose to play an Anime trivia Game.

### ISSUE THREAD

**Issue by Youssef-Najjarine** [Youssef-Najjarine/anime-fans#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see a random trivia question appear after clicking the Anime Trivia Button.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see a random trivia question appear after clicking the Anime Trivia Button.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71291742/125547161-cab8770f-0a69-4aee-87f6-37e948176f37.png)

## ✅ Task List

- [x] User can view a random quote in Trivia game.
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
