### ISSUE TITLE
User can submit an answer

### ISSUE THREAD

**Issue by Youssef-Najjarine** [Youssef-Najjarine/anime-fans#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to submit an answers for the trivia question. If one of the answers are correct a correct modal with the answer will pop up. If both answers are incorrect, an incorrect modal will pop up with the correct answer.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

 After hitting the submit button, one of two modals popped up displaying whether or not one of my answers were correct.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71291742/125547506-afacb5a0-d5e7-4a2c-b8ff-f6282e4d2b5a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can choose to guess the name of the character that said the quote.
- [x] User can choose to guess the Anime series that the quote is from.
- [x] Once User submits an answer an incorrect or correct screen pops up with the correct answer.
- [x] After clicking the next button a new random quote appears.
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
