### ISSUE TITLE
User can favorite an Anime quote/Anime

### ISSUE THREAD

**Issue by Youssef-Najjarine** [Youssef-Najjarine/anime-fans#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to favorite a quote that they like by clicking the heart button next to each Anime. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can favorite any Anime that they like and go to "my favorites" to view them.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71291742/125547956-f3496943-1785-4bbd-9b06-ddd0ad444d7d.png)
![image](https://user-images.githubusercontent.com/71291742/125547966-139c76b8-5b1b-489c-8aa2-ce3d82b3313b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When user clicks on heart button next to Anime quote it saves it to a data variable that is stored in local storage.
- [x] User can view a list of their favorite Animes.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
