### ISSUE TITLE
Optional: User can choose the “rate/review” at Home screen

### ISSUE THREAD

**Issue by Youssef-Najjarine** [Youssef-Najjarine/anime-fans#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to view multiple Animes displayed on the "Review Animes" page.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the User clicks the "Rate&Review Animes" button on the home page, it will take them to the "Review Animes" page where multiple Animes will be listed for the User to review. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71291742/125548514-ec134e36-fd0d-446a-9723-e424a588a0e4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] 20 random Animes appear after clicking the “rate and review” button.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
