### ISSUE TITLE
Optional: User can give each Anime a rating out of 5 stars.

### ISSUE THREAD

**Issue by Youssef-Najjarine** [Youssef-Najjarine/anime-fans#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to hover over any of the star and it will light up yellow. If User clicks on any of the stars all the stars leading up to the star clicked on and including the one clicked will permanently stay yellow.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to hover over any of the star and it will light up yellow. If User clicks on any of the stars all the stars leading up to the star clicked on and including the one clicked will permanently stay yellow.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71291742/125548921-52f99cff-f2fa-4c2e-8d07-8b3bc1288727.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When User hovers over stars it lights up as a yellow star.
- [x] If User clicks a star it gets permanently changed to a yellow star.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
