### ISSUE TITLE
Optional: User can write their own review for each Anime.

### ISSUE THREAD

**Issue by Youssef-Najjarine** [Youssef-Najjarine/anime-fans#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The User can write a review for each of the Animes and submit it. Once submited the Anime disappears and a new one takes it's place.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The User can write a review for each of the Animes and submit it.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71291742/125549209-ecb25d03-b879-4ee4-b917-812e60aa6add.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Submitting their review gets rid of current Anime and displays a new one to be reviewed.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
